# Generated by Django 3.2.23 on 2023-11-06 09:06
# Generated by Django 3.2.4 on 2023-12-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PgcronnerJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('command', models.TextField()),
                ('schedule', models.CharField(max_length=255)),
                ('source', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'PgCronner Job',
                'verbose_name_plural': 'PgCronner Jobs',
                'db_table': 'pgcronner_jobs',
                'managed': False,
            },
        ),
    ]

