# Generated by Django 3.2.23 on 2023-11-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pgcronnerjobs',
            options={'managed': True},
        ),
    ]
