# Generated by Django 3.2.23 on 2023-11-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pgcronnerjobs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pgcronnerjobs',
            options={},
        ),
        migrations.AlterField(
            model_name='pgcronnerjobs',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
